### ISSUE TITLE
[Bug] Argument Parsing Issue for Windows in README Example

### ISSUE THREAD

**Issue by breadgrocery** [tomwis/CommitLint.Net#5]
First of all, thank you for your hard work. This project is useful, and I like it.

In the README, the example command for running Husky is written as:

```
# dotnet husky add commit-msg -c "dotnet husky run --group commit-msg --args \"\$1\""
dotnet husky run --group commit-msg --args "\$1"
```

However, on Windows, this syntax causes an issue where husky receives the literal string $1 instead of the intended argument.
To fix this, the correct command for Windows should be: 

```
# $1 stands for the location of  `COMMIT_EDITMSG` file
dotnet husky run --group commit-msg --args $1
```

**Comment by breadgrocery** [comment]
It would be great if the NuGet package page for this project included a **Project website** link to the project's repository.
Spent a bit of time searching for it.

**Comment by tomwis** [comment]
Thank you for taking time to post this issue. I updated instructions for Windows and made it clear how final command should look like.

Issue was closed when PR was merged, but I will make changes in NuGet package as you requested in your second comment as well.

**Comment by breadgrocery** [comment]
It seems you misunderstood, what I mean is that $1 doesn't need to be **quoted** on Windows.
In the end, entry in commit-msg file that will be created by dotnet husky add should be:
```
dotnet husky run --group commit-msg --args $1
```
Otherwise, the value of **${args}** will be the string $1, rather than the path of COMMIT_EDITMSG

**Comment by tomwis** [comment]
> It seems you misunderstood, what I mean is that $1 doesn't need to be
> *quoted* on Windows.

It doesn't need to be quoted on Mac as well, but it is just a safeguard
against spaces in the path of the commit message file. I tested both
commands, with or without quotes, on Windows and they work for me the same
way (assuming there is no space in the commit message path). Did you have
different experience? I tested it in the built-in command prompt and in
Rider's terminal (which is running PowerShell from what I see).

Also, original command from readme (for Mac), produced following result on
Windows (at least for me):

> dotnet husky run --group commit-msg --args " \\ # from Rider's terminal
> dotnet husky run --group commit-msg --args "\$1" # from Command Prompt


So it was invalid anyway, even ignoring quotes. Was it the same for you? Or
maybe there are some more discrepancies?
And now I noticed that my fix in readme is working in PowerShell, but not
in CommandPrompt :D Oh, well. For Command Prompt this should be fine:

> dotnet husky add commit-msg -c "dotnet husky run --group commit-msg --args \"$1\"" 

There is no backslash before dollar sign.

> Otherwise, the value of *${args}* will be the string $1, rather than the path of COMMIT_EDITMSG

Would be nice to know your environment if you were getting $1
string instead of path, because maybe something is working differently
there. I could update docs accordingly or maybe just point to Husky.NET
docs, but I don't think it is described anywhere there.

**Comment by breadgrocery** [comment]
I’m not sure what’s going on, but at least the README description is accurate now (except for CMD).


The strange part is that  I used the original command in PowerShell, and it worked, creating this:
```
dotnet husky run --group commit-msg --args "$1"
```

But now, it creates this:
```
dotnet husky run --group commit-msg --args " \\
```

After commenting it out, I tested again (modified the file manually) and found that quoted $1 also works. 

So, I removed the comment, but you were still notified by email, haha.

Now I can't reproduce the issue anymore, so let's just move on. At least it's correct now.
